<a href="https://colab.research.google.com/github/KSanders-data/KaitlynSanders_DTSC3020_Summer2026/blob/main/3010Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
w=np.array([1,2,3])
x=np.array([0,1,1])
print(np.multiply(w,x))

import numpy as np
A=np.array([[1,4],[3,9]])
B=np.array([[1,0,0],[2,1,3],[0,0,1]])
print("Inverse A", np.linalg.inv(A))
print("Inverse B", np.linalg.inv(B))

import numpy as np
a=np.array([[3,1],[9,4]])
b=np.array([3,6])
x=np.linalg.solve(a,b)
print("Solution", x)

[0 2 3]
Inverse A [[-3.          1.33333333]
 [ 1.         -0.33333333]]
Inverse B [[ 1.  0.  0.]
 [-2.  1. -3.]
 [ 0.  0.  1.]]
Solution [ 2. -3.]
